author: JoshuaKGoldberg
branding:
  color: purple
  icon: award
description: Fills in missing allcontributors entries for a repository. 👪
name: All Contributors Auto Action
runs:
  main: dist/index.js
  using: node20
